// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVs383Enphto4NCnkhe1Qp9KffpKqdKUk',
    appId: '1:115028851403:web:c704c681da9dcb5b0c394e',
    messagingSenderId: '115028851403',
    projectId: 'meditopia-9abd1',
    authDomain: 'meditopia-9abd1.firebaseapp.com',
    storageBucket: 'meditopia-9abd1.appspot.com',
    measurementId: 'G-7PVVQJVRER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnaJKd13CRZhSN0Jk08i3YQaVCj0cLWG8',
    appId: '1:115028851403:android:cb5ce3ab54bc57c90c394e',
    messagingSenderId: '115028851403',
    projectId: 'meditopia-9abd1',
    storageBucket: 'meditopia-9abd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj4j8jvie8CJ_uFNDQtJcZN3AJZYB5XRU',
    appId: '1:115028851403:ios:0d11ae0397a831f80c394e',
    messagingSenderId: '115028851403',
    projectId: 'meditopia-9abd1',
    storageBucket: 'meditopia-9abd1.appspot.com',
    iosClientId: '115028851403-d63flvda8qq1rgfbmq6fciq6jiuhltc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.meditopia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj4j8jvie8CJ_uFNDQtJcZN3AJZYB5XRU',
    appId: '1:115028851403:ios:0d11ae0397a831f80c394e',
    messagingSenderId: '115028851403',
    projectId: 'meditopia-9abd1',
    storageBucket: 'meditopia-9abd1.appspot.com',
    iosClientId: '115028851403-d63flvda8qq1rgfbmq6fciq6jiuhltc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.meditopia',
  );
}
